services:
  server:
    container_name: video-backend
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    restart: always

  node-exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter
    environment:
      DATA_SOURCE_NAME: "postgresql://{{ username }}:{{ password }}@{{ host }}:{{ port }}/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    restart: always

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    restart: always
