services:
  db:
    image: postgres:15
    container_name: video-db
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/initdb.sql:/docker-entrypoint-initdb.d/init.sql

    ports:
      - "5432:5432"

  server:
    container_name: video-backend
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  db-data:
