version: '3.9'

services:
  db:
    image: postgres:15
    container_name: video-db
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    container_name: video-backend
    build: .
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"

volumes:
  db-data:
