global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'node'
  static_configs:
  - targets: [ '56.228.17.88:9100' ] 

- job_name: 'cadvisor'
  static_configs:
  - targets: [ '56.228.17.88:8080' ]

- job_name: 'postgres-exporter'
  static_configs:
  - targets: [ '56.228.17.88:9187' ]
