global:
  scrape_interval: 15s

scrape_configs:
- job_name: 'node'
  static_configs:
  - targets: [ '13.61.196.184:9100' ] 

- job_name: 'cadvisor'
  static_configs:
  - targets: [ '13.61.196.184:8080' ]

- job_name: 'postgres-exporter'
  static_configs:
  - targets: [ '13.61.196.184:9187' ]
