name: Deploy to EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: npm install

      # - name: Build website
      #   run: npm run build

      # - name: Install AWS CLI
      #   run: sudo apt-get install -y awscli

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Copy to EC2
        run: aws ec2 run-instances --image-id ami-0d70546e43a941d70 --instance-type t2.micro
