name: Deploy to EC2
on:
  push: 
    branches: 
      - main

jobs: 
  deploy: 
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm --workspace server run build

      - name: Install AWS CLI
        run: sudo apt-get install -y awscli

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: What folder am I in?
        run: pwd

      - name: What folders exist here?
        run: ls -la

      - name: Copy to EC2
        run: aws ec2 sync ./static s3://full-stack-project
