---
name: Deploy to EC2
'on':
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd /home/ubuntu
            if [ ! -d "Adniya-Full-Stack-Project" ];
            then
            git clone https://github.com/adniyaYousaf/Adniya-Full-Stack-Project.git
            fi
            sudo apt update
            sudo apt install -y nodejs npm
            cd Adniya-Full-Stack-Project
            cd client
            npm install 
            npm run build 
            cd ../server
            sudo npm install -g pm2
            pm2 start npm --name "adniya-server" -- run dev
