name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  build:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: checkout repository
        uses: actions/checkout@v3
      - name: install dependencies
        run: npm ci
      - name: build code
        run: npm run build
      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist files
          path: dist


  deploy:
    needs: build
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: Install AWS CLI
        run: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip3 install --upgrade awscli
      - name: set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2
      - name: download artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist files
      - name: what does dist folders have?
        run: ls
      - name: copy to S3
        run: aws s3 sync ../server/static/. s3://video-recommendation-project
