name: week 3

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DATABASE_URL : "DATABASE_URL"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo apt update
            sudo apt install -y docker.io

            sudo systemctl start docker
            sudo systemctl enable docker

            sudo curl -L "https://github.com/docker/compose/releases/download/v2.24.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            cd /home/ubuntu

            # Clone or pull the latest project
            if [ ! -d "Adniya-Full-Stack-Project" ]; then
              git clone https://github.com/adniyaYousaf/Adniya-Full-Stack-Project.git
            fi

            cd Adniya-Full-Stack-Project
            git pull

            # Restart Docker Compose services
            sudo docker-compose down -v
            sudo docker-compose up -d --build

