name: week 3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Docker and Git are installed
            sudo apt update
            sudo apt install -y docker.io

            # Start Docker
            sudo systemctl start docker
            sudo systemctl enable docker

            # Navigate to home directory
            cd /home/ubuntu
            # Clone or update the project
            if [ ! -d "Adniya-Full-Stack-Project" ]; then
            git clone https://github.com/adniyaYousaf/Adniya-Full-Stack-Project.git
            fi

            cd Adniya-Full-Stack-Project
            git pull
            echo "${{ secrets.DATABASE_URL}}" > /home/ubuntu/Adniya-Full-Stack-Project/.env

            # Run Docker Compose
            sudo docker compose down -v
            sudo docker compose up -d --build
            sudo docker compose up
