name: week 3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # Ensure Docker and Git are installed
            sudo apt update
            sudo apt install -y docker.io git curl

            # Install Docker Compose v2 under root's docker CLI plugins
            sudo mkdir -p /root/.docker/cli-plugins
            sudo curl -SL https://github.com/docker/compose/releases/download/v2.27.0/docker-compose-linux-x86_64 \
            -o /root/.docker/cli-plugins/docker-compose
            sudo chmod +x /root/.docker/cli-plugins/docker-compose

            # Start Docker
            sudo systemctl start docker
            sudo systemctl enable docker

            # Navigate to home directory
            cd /home/ubuntu

            # Clone or update the project
            if [ ! -d "Adniya-Full-Stack-Project" ]; then
            git clone https://github.com/adniyaYousaf/Adniya-Full-Stack-Project.git
            fi

            cd Adniya-Full-Stack-Project
            git pull --ff-only origin main

            # Run Docker Compose
            sudo docker compose down
            sudo docker compose pull
            sudo docker compose up -d --build
